name: CI

on: [push, pull_request]
       
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Install Fish
        run: |
          sudo apt-add-repository -yn ppa:fish-shell/release-3
          sudo apt-get update
          sudo apt-get install -y fish

      - name: Install Reef and run tests
        run: |
          cd "$GITHUB_WORKSPACE"
          curl -sL https://tinyurl.com/fish-reef | source
          reef init
          reef add jorgebucaran/fishtape
          fishtape test/*.fish
        shell: fish {0}
